### ISSUE TITLE
8. Test screening setup

### ISSUE THREAD

**Issue by andrasvereckei** [korenmiklos/2020-08-23-eea#9]

**Comment by korenmiklos** [comment]
I have tried sharing part of screen via Zoom and recording it. The recording came out well, a narrow video, with the "talking head" in the top right. This can be a good setup, but needs to be tested on different sized screens.

**Comment by korenmiklos** [comment]
I recommend using a portrait layout for screen sharing so that students have space on their screen to open their own shell/Stata. We will encourage dual screens, but not all will be able to do it. In Zoom, click on "Share screen," "Advanced," and "Portion of screen." This way you can select a fixed rectangle on your screen to share. Make sure to move applications around your screen *before* you begin the class.

Use dark font on white background and at least 18p-sized font. Set this in advance for both Bash and for Stata.

**Comment by korenmiklos** [comment]
Zoom host can make others host or co-host. Even if host's network breaks down, meeting stays online. There are polling buttons under "Participants", which can be used to substitute for green and red stickies. Zoom aggregates poll results there.

**Comment by korenmiklos** [comment]
On the iMac, I am using a 1.5x magnification for the overall screen, and 16p font in Stata, 20p font in bash. Make sure to leave some space at the bottom for Zoom buttons.
